#!/bin/bash
# Generated by pentest-mcp — review before running
# Run as root or with sudo

set -e

echo "Installing security tools for pentest-mcp..."
echo ""

# APT tools
echo "Installing APT packages..."
apt update
apt install -y nmap masscan nikto gobuster ffuf whatweb hydra amass testssl.sh

# pip tools
echo ""
echo "Installing Python packages..."
pip install sqlmap wfuzz arjun corscanner commix dnsrecon sslyze wafw00f \
    theHarvester shodan trufflehog git-dumper enum4linux-ng graphql-cop jwt_tool xsstrike

# Go tools
echo ""
echo "Installing Go tools..."
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
go install github.com/hahwul/dalfox/v2@latest
go install github.com/trufflesecurity/trufflehog@latest

# npm tools
echo ""
echo "Installing npm packages..."
npm install -g retire

echo ""
echo "✓ Installation complete!"
echo "Restart your terminal and run: pentest session init --target <url> --consent"
